name: Feature Request
description: Request a feature
title: "Enhancement"
labels: ["enhancement", "triage"]
assignees:
  - marek-saji
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project. 🙂
        Please note that this is a pet project and I’m not actively using it on my day to day. I am commited to fixing bugs when they arise, but implementing new features is unlikely. Pull requests with new features are welcome though.
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: |
        Please describe what problem a feature you are requwsting is aiming to solve.
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How?
      description: |
        How do you image the solution to that problem?
    validations:
      required: false
